on: 
  workflow_dispatch: 
  pull_request: {}
  push:
    branches:
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 00 5 1 * *
name: Semgrep
jobs:
  buildmavenDepTree: 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Build Dependency Tree
        run: mvn dependency:tree -DoutputFile=maven_dep_tree.txt
      - name: Create Zip File
        run: zip -r archive.zip maven_dep_tree.txt
      - name: Upload Dependency Tree Artifact     
        uses: actions/upload-artifact@v3
        with:
          name: mavendeptree
          path: maven_dep_tree.txt
      - name: Upload Dependency Zip    
        uses: actions/upload-artifact@v3
        with:
          name: zipfile
          path: archive.zip
  semgrep:
    needs: buildmavenDepTree
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact from previous job 1
        uses: actions/download-artifact@v3
        with:
          name: mavendeptree
      - name: Download artifact from previous job 2
        uses: actions/download-artifact@v3
        with:
          name: zipfile      
      - run: |
          ls -la
          semgrep ci
